name: ncaltech101
path: dataset/ncaltech # /net/scratch/hscra/plgrid/plgjeziorek/Datasets/N-Caltech/N-Caltech101_dat
general:
  org_dim: [240, 180]
  num_classes: 100
  time_window: 50000 # us

train:
  batch_size: 2
  num_workers: 2
  lr: 0.0001
  weight_decay: 0.0001
  epochs: 100
  optimizer: adamW

augmentation:
  h_flip:
    p: 0.5
  random_crop:
    p: 0.5
    size: [0.75, 0.75]
    dim: [0, 1]
  random_zoom:
    zoom: [1, 1]
    subsample: True
  translate:
    size: [0.1, 0.1]
  crop:
    min: [0, 0]
    max: [1, 1]

representation:
  type: ???
  event_frame:
    dim: [240, 180]
  event_voxel:
    time_window: 10
    dim: [240, 180]
  event_graph:
    radius: 5
    dim: [240, 180]

    